### ISSUE TITLE
default.css not removed on portal/0

### ISSUE THREAD

**Issue by leedavi** [40fingers/StyleHelper-Sko#34]
We've added a rule to remove the default.css from the website when no users are logged in.

This works ok for all portals, but portal/0 still does not display the default.css when the superuser is logged in.

However, If a normal user logs in with a normal roles, the default.css is injected, like expected.

We have never noticed this before, we are running DNN9.11.

We also do not have a SSL cert, on portal/0. (not for public viewing)  We thought this may be causing the problem.

**Comment by Timo-Breumelhof** [comment]
And you are using version 02.15.03 right?
Are you saying this is only an issue on Portal 0 or did you just notice it on Portal 0?

**Comment by leedavi** [comment]
I was told it's the latest version... not checked that.  
Yes, this only effected portal/0 and only the SuperUser.
It's not a showstopper, but very odd.   Maybe there is something wring with our installation, but it's a new version off DNN9.11 with only 1 website on it.

**Comment by leedavi** [comment]
This was a installation with about 5 websites on it, all worked apart from portal/0 with the SuperUser.

**Comment by Timo-Breumelhof** [comment]
Can you post what you added to the skin?

**Comment by Timo-Breumelhof** [comment]
As an FYI, if you want to check for Superusers you need to use IfRole="SuperUsers" as the role.
When you create a portal as a superuser, it can be that the Host is also in the Administrator role, which could cause the difference between portal 0 and the rest of the Portals?

**Comment by leedavi** [comment]
We use IfRole="None"

As for portal/0  I "think" we usually make all portals have the host as Administrator.  I cannot think of any reason SuperUser should be different on portal/0, but there is obviously something different.

**Comment by leedavi** [comment]
I'll close this, because I don't think we should waste time on it.  We have a work around.  But I thought I would mention it for someone else finding the problem.

**Comment by Timo-Breumelhof** [comment]
Actually I see now that "none" can also match a Superuser as depending on the way the portal was created a Host can be in no roles. Not very  logical and there's code to "fake the Superuser" role, but I'll change the order as the check for None is before that..

**Comment by leedavi** [comment]
OK, thx.  Let us know when you've done it and we'll test it for you.
