### ISSUE TITLE
Default.css is everywhere!!!

### ISSUE THREAD

**Issue by leedavi** [40fingers/StyleHelper-Sko#35]
![image](https://user-images.githubusercontent.com/5583141/207897843-1c3df989-f76e-47fd-896b-079e139cc334.png)

![image](https://user-images.githubusercontent.com/5583141/207897963-74957649-904c-4889-9180-9579fed99813.png)

Ouch!!!!  Timo.... Ouch!!!!  :-)

**Comment by Timo-Breumelhof** [comment]
Just be more specific, pass "/Resources/Shared/stylesheets/dnndefault/7.0.0/default.cs" for instance..

**Comment by leedavi** [comment]
The issue is that "MarkCluster.Default.css" is removed, because we remove the "Default.css" file when the user is not logged in.

Like in your documentation, because the line contains "default.css", it is removed.  But we need "MarkCluster.Default.css".

We have had to host it local and rename it to stop style helper from removing it.

It would be nice to have wildcard expressions, so we can match the full file name "Default.css" instead of anything matching a part of the path.

I wonder if "/Default.css" will work.  I'll ask Frank to try.

**Comment by leedavi** [comment]
Try undocumented wold card.
RemoveCssFile="/Resources/Shared/stylesheets/.*/default.css"

**Comment by Timo-Breumelhof** [comment]
It's documented now :-)

![image](https://user-images.githubusercontent.com/8999382/208084445-cc38b16b-a4be-4f4e-89e8-c10fcb8ce906.png)

**Comment by leedavi** [comment]
Thank you Timo.  Great work.
